// Item definitions. Data-only: plain objects, no logic.
//
// Equipment requirements deviate slightly from OSRS for early-game pacing:
// bronze tier is unrestricted, iron tier requires attack 5 and steel tier
// requires attack 10 (so requirement gating is exercised from the very start
// of the game). Gathering tools follow the same pacing: bronze tools are
// usable at level 1, iron tools require level 5 and steel tools require
// level 10 in the matching gather skill.
import type { ItemDef } from './types'

export const items: Record<string, ItemDef> = {
  coins: {
    id: 'coins',
    name: 'Coins',
    examine: 'Lovely money!',
    stackable: true,
    value: 1,
  },
  bronze_axe: {
    id: 'bronze_axe',
    name: 'Bronze axe',
    examine: 'A woodcutting axe.',
    stackable: false,
    value: 16,
    tool: { kind: 'axe', tier: 1, requiredLevel: 1 },
    equipment: {
      slot: 'weapon',
      bonuses: { attackSlash: 3, attackCrush: 1, meleeStrength: 2 },
      attackSpeed: 4,
      attackType: 'slash',
    },
  },
  iron_axe: {
    id: 'iron_axe',
    name: 'Iron axe',
    examine: 'A woodcutting axe.',
    stackable: false,
    value: 56,
    tool: { kind: 'axe', tier: 2, requiredLevel: 5 },
    equipment: {
      slot: 'weapon',
      requirements: { attack: 5 },
      bonuses: { attackSlash: 5, attackCrush: 2, meleeStrength: 4 },
      attackSpeed: 4,
      attackType: 'slash',
    },
  },
  steel_axe: {
    id: 'steel_axe',
    name: 'Steel axe',
    examine: 'A woodcutting axe.',
    stackable: false,
    value: 200,
    tool: { kind: 'axe', tier: 3, requiredLevel: 10 },
    equipment: {
      slot: 'weapon',
      requirements: { attack: 10 },
      bonuses: { attackSlash: 7, attackCrush: 3, meleeStrength: 6 },
      attackSpeed: 4,
      attackType: 'slash',
    },
  },
  bronze_pickaxe: {
    id: 'bronze_pickaxe',
    name: 'Bronze pickaxe',
    examine: 'Used for mining.',
    stackable: false,
    value: 1,
    tool: { kind: 'pickaxe', tier: 1, requiredLevel: 1 },
    equipment: {
      slot: 'weapon',
      bonuses: { attackStab: 4, attackCrush: 2, meleeStrength: 3 },
      attackSpeed: 5,
      attackType: 'stab',
    },
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Iron pickaxe',
    examine: 'Used for mining.',
    stackable: false,
    value: 140,
    tool: { kind: 'pickaxe', tier: 2, requiredLevel: 5 },
    equipment: {
      slot: 'weapon',
      requirements: { attack: 5 },
      bonuses: { attackStab: 6, attackCrush: 3, meleeStrength: 4 },
      attackSpeed: 5,
      attackType: 'stab',
    },
  },
  steel_pickaxe: {
    id: 'steel_pickaxe',
    name: 'Steel pickaxe',
    examine: 'Used for mining.',
    stackable: false,
    value: 500,
    tool: { kind: 'pickaxe', tier: 3, requiredLevel: 10 },
    equipment: {
      slot: 'weapon',
      requirements: { attack: 10 },
      bonuses: { attackStab: 8, attackCrush: 4, meleeStrength: 6 },
      attackSpeed: 5,
      attackType: 'stab',
    },
  },
  small_fishing_net: {
    id: 'small_fishing_net',
    name: 'Small fishing net',
    examine: 'Useful for catching small fish.',
    stackable: false,
    value: 5,
    tool: { kind: 'net', tier: 1, requiredLevel: 1 },
  },
  tinderbox: {
    id: 'tinderbox',
    name: 'Tinderbox',
    examine: 'Useful for lighting a fire.',
    stackable: false,
    value: 1,
  },
  bronze_sword: {
    id: 'bronze_sword',
    name: 'Bronze sword',
    examine: 'A razor sharp sword.',
    stackable: false,
    value: 26,
    equipment: {
      slot: 'weapon',
      bonuses: { attackStab: 4, attackSlash: 3, defenceStab: 2, meleeStrength: 5 },
      attackSpeed: 5,
      attackType: 'stab',
    },
  },
  bronze_scimitar: {
    id: 'bronze_scimitar',
    name: 'Bronze scimitar',
    examine: 'A vicious, curved sword.',
    stackable: false,
    value: 32,
    equipment: {
      slot: 'weapon',
      bonuses: { attackSlash: 7, attackStab: 1, meleeStrength: 6 },
      attackSpeed: 4,
      attackType: 'slash',
    },
  },
  bronze_2h_sword: {
    id: 'bronze_2h_sword',
    name: 'Bronze 2h sword',
    examine: 'A sword requiring two hands to wield.',
    stackable: false,
    value: 84,
    equipment: {
      slot: 'weapon',
      twoHanded: true,
      bonuses: { attackSlash: 7, attackCrush: 6, attackStab: -4, meleeStrength: 10 },
      attackSpeed: 7,
      attackType: 'slash',
    },
  },
  wooden_shield: {
    id: 'wooden_shield',
    name: 'Wooden shield',
    examine: 'A solid wooden shield.',
    stackable: false,
    value: 20,
    equipment: {
      slot: 'shield',
      bonuses: {
        defenceStab: 4,
        defenceSlash: 5,
        defenceCrush: 3,
        defenceMagic: -1,
        defenceRanged: 4,
      },
    },
  },
  bronze_full_helm: {
    id: 'bronze_full_helm',
    name: 'Bronze full helm',
    examine: 'A full face helmet.',
    stackable: false,
    value: 44,
    equipment: {
      slot: 'head',
      bonuses: {
        defenceStab: 4,
        defenceSlash: 5,
        defenceCrush: 3,
        defenceMagic: -1,
        defenceRanged: 4,
        attackMagic: -6,
        attackRanged: -2,
      },
    },
  },
  bronze_platebody: {
    id: 'bronze_platebody',
    name: 'Bronze platebody',
    examine: 'Provides excellent protection.',
    stackable: false,
    value: 160,
    equipment: {
      slot: 'body',
      bonuses: {
        defenceStab: 15,
        defenceSlash: 14,
        defenceCrush: 9,
        defenceMagic: -6,
        defenceRanged: 14,
        attackMagic: -30,
        attackRanged: -10,
      },
    },
  },
  bronze_platelegs: {
    id: 'bronze_platelegs',
    name: 'Bronze platelegs',
    examine: 'These look pretty heavy.',
    stackable: false,
    value: 80,
    equipment: {
      slot: 'legs',
      bonuses: {
        defenceStab: 8,
        defenceSlash: 7,
        defenceCrush: 5,
        defenceMagic: -4,
        defenceRanged: 7,
        attackMagic: -21,
        attackRanged: -7,
      },
    },
  },
  logs: {
    id: 'logs',
    name: 'Logs',
    examine: 'A number of wooden logs.',
    stackable: false,
    value: 4,
  },
  oak_logs: {
    id: 'oak_logs',
    name: 'Oak logs',
    examine: 'Logs cut from an oak tree.',
    stackable: false,
    value: 20,
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Copper ore',
    examine: 'This needs refining.',
    stackable: false,
    value: 3,
  },
  tin_ore: {
    id: 'tin_ore',
    name: 'Tin ore',
    examine: 'This needs refining.',
    stackable: false,
    value: 3,
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron ore',
    examine: 'This needs refining.',
    stackable: false,
    value: 17,
  },
  steel_ore: {
    id: 'steel_ore',
    name: 'Steel ore',
    examine: 'This needs refining.',
    stackable: false,
    value: 34,
  },
  bronze_bar: {
    id: 'bronze_bar',
    name: 'Bronze bar',
    examine: "It's a bar of bronze.",
    stackable: false,
    value: 8,
  },
  iron_bar: {
    id: 'iron_bar',
    name: 'Iron bar',
    examine: "It's a bar of iron.",
    stackable: false,
    value: 17,
  },
  steel_bar: {
    id: 'steel_bar',
    name: 'Steel bar',
    examine: "It's a bar of steel.",
    stackable: false,
    value: 34,
  },
  raw_shrimps: {
    id: 'raw_shrimps',
    name: 'Raw shrimps',
    examine: 'I should try cooking these.',
    stackable: false,
    value: 5,
  },
  shrimps: {
    id: 'shrimps',
    name: 'Shrimps',
    examine: 'Some nicely cooked shrimps.',
    stackable: false,
    value: 5,
    healAmount: 3,
  },
  burnt_shrimps: {
    id: 'burnt_shrimps',
    name: 'Burnt shrimps',
    examine: 'Oops!',
    stackable: false,
    value: 1,
  },
  raw_trout: {
    id: 'raw_trout',
    name: 'Raw trout',
    examine: 'I should try cooking this.',
    stackable: false,
    value: 20,
  },
  trout: {
    id: 'trout',
    name: 'Trout',
    examine: 'Some nicely cooked trout.',
    stackable: false,
    value: 20,
    healAmount: 7,
  },
  burnt_trout: {
    id: 'burnt_trout',
    name: 'Burnt trout',
    examine: 'Oops!',
    stackable: false,
    value: 1,
  },
  bones: {
    id: 'bones',
    name: 'Bones',
    examine: 'Bones are for burying!',
    stackable: false,
    value: 1,
    buryXp: 4.5,
  },
  cowhide: {
    id: 'cowhide',
    name: 'Cowhide',
    examine: 'I should take this to the tannery.',
    stackable: false,
    value: 1,
  },
  raw_beef: {
    id: 'raw_beef',
    name: 'Raw beef',
    examine: 'I should try cooking this.',
    stackable: false,
    value: 1,
  },
  cooked_beef: {
    id: 'cooked_beef',
    name: 'Cooked beef',
    examine: 'Mmm, this looks tasty.',
    stackable: false,
    value: 4,
    healAmount: 3,
  },
  burnt_beef: {
    id: 'burnt_beef',
    name: 'Burnt beef',
    examine: 'Oops!',
    stackable: false,
    value: 1,
  },
  raw_chicken: {
    id: 'raw_chicken',
    name: 'Raw chicken',
    examine: 'I need to cook this before eating it.',
    stackable: false,
    value: 1,
  },
  cooked_chicken: {
    id: 'cooked_chicken',
    name: 'Cooked chicken',
    examine: 'Mmm, this looks tasty.',
    stackable: false,
    value: 4,
    healAmount: 3,
  },
  burnt_chicken: {
    id: 'burnt_chicken',
    name: 'Burnt chicken',
    examine: 'Oops!',
    stackable: false,
    value: 1,
  },
  feather: {
    id: 'feather',
    name: 'Feather',
    examine: 'Used for fly fishing.',
    stackable: true,
    value: 2,
  },
  leather: {
    id: 'leather',
    name: 'Leather',
    examine: 'A piece of tanned cowhide.',
    stackable: false,
    value: 20,
  },
  needle: {
    id: 'needle',
    name: 'Needle',
    examine: 'Used with thread to make leather items.',
    stackable: false,
    value: 1,
  },
  thread: {
    id: 'thread',
    name: 'Thread',
    examine: 'Used to make things.',
    stackable: true,
    value: 1,
  },
  leather_gloves: {
    id: 'leather_gloves',
    name: 'Leather gloves',
    examine: 'These will keep my hands warm!',
    stackable: false,
    value: 6,
    equipment: {
      slot: 'hands',
      bonuses: { defenceStab: 1, defenceSlash: 1, defenceCrush: 1 },
    },
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather boots',
    examine: 'Comfortable leather boots.',
    stackable: false,
    value: 6,
    equipment: {
      slot: 'feet',
      bonuses: { defenceStab: 1, defenceSlash: 1, defenceCrush: 1 },
    },
  },
  leather_body: {
    id: 'leather_body',
    name: 'Leather body',
    examine: 'It provides some protection.',
    stackable: false,
    value: 25,
    equipment: {
      slot: 'body',
      bonuses: { defenceStab: 4, defenceSlash: 4, defenceCrush: 4, defenceRanged: 4 },
    },
  },
  leather_chaps: {
    id: 'leather_chaps',
    name: 'Leather chaps',
    examine: 'Fine leather chaps.',
    stackable: false,
    value: 20,
    equipment: {
      slot: 'legs',
      bonuses: { defenceStab: 2, defenceSlash: 2, defenceCrush: 2, defenceRanged: 2 },
    },
  },
  knife: {
    id: 'knife',
    name: 'Knife',
    examine: 'A sharp knife, useful for fletching.',
    stackable: false,
    value: 6,
  },
  arrow_shafts: {
    id: 'arrow_shafts',
    name: 'Arrow shafts',
    examine: 'Some carefully cut arrow shafts.',
    stackable: true,
    value: 1,
  },
  shortbow_u: {
    id: 'shortbow_u',
    name: 'Shortbow (u)',
    examine: 'An unstrung shortbow; it needs a string.',
    stackable: false,
    value: 5,
  },
  longbow_u: {
    id: 'longbow_u',
    name: 'Longbow (u)',
    examine: 'An unstrung longbow; it needs a string.',
    stackable: false,
    value: 10,
  },
  oak_shortbow_u: {
    id: 'oak_shortbow_u',
    name: 'Oak shortbow (u)',
    examine: 'An unstrung oak shortbow; it needs a string.',
    stackable: false,
    value: 20,
  },
}
